services:
  smtpd-cloudflare:
    container_name: smtpd-cloudflare
    build: ./
    ports:
      - "587:2525"
    volumes:
      - smtpd-cloudflare-acme:/usr/src/app/acme
    environment:
      - "HOST=0.0.0.0"
      - "PORT=2525"
      - "SMTP_USERNAME=asd"
      - "SMTP_PASSWORD=asd"
      - "CLOUDFLARE_ACCOUNT_ID="
      - "CLOUDFLARE_ZONE_ID="
      - "CLOUDFLARE_API_EMAIL_TOKEN="
      - "CLOUDFLARE_API_DNS_TOKEN="
      - "RUBY_ENV=development"
      - "EXCEPTION_REPORTING_EMAIL="
      - "DOMAIN="
      - "ACME_URL=https://acme-staging-v02.api.letsencrypt.org/directory"

volumes:
  smtpd-cloudflare-acme:
    name: smtpd-cloudflare-acme
