services:
  smtpd-cloudflare:
    container_name: smtpd-cloudflare
    build: ./
    ports:
      - "587:2525"
    volumes:
      - smtpd-cloudflare-acme:/usr/src/app/acme
    environment:
      - "PORT=2525"

volumes:
  smtpd-cloudflare-acme:
    name: smtpd-cloudflare-acme
